apiVersion: ecc.aws.gotopple.com/v1alpha1
kind: VPC
metadata:
  name: example-network
spec:
  cidrBlock: "10.20.0.0/16"
  enableDnsSupport: true
  enableDnsHostnames: true
  instanceTenancy: default
  tags:
    - key: Name
      value: my-super-vpc2
---
apiVersion: ecc.aws.gotopple.com/v1alpha1
kind: Subnet
metadata:
  name: example-network-public-a
spec:
  vpcName: example-network
  availabilityZone: "us-west-2a"
  cidrBlock: "10.20.110.0/24"
  tags:
   - key: Name
     value: public-a
---
apiVersion: ecc.aws.gotopple.com/v1alpha1
kind: Subnet
metadata:
  name: example-network-public-b
spec:
  vpcName: example-network
  availabilityZone: "us-west-2b"
  cidrBlock: "10.20.120.0/24"
  tags:
   - key: Name
     value: public-b
---
apiVersion: ecc.aws.gotopple.com/v1alpha1
kind: Subnet
metadata:
  name: example-network-public-c
spec:
  vpcName: example-network
  availabilityZone: "us-west-2c"
  cidrBlock: "10.20.130.0/24"
  tags:
   - key: Name
     value: public-c
