apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: eipassociations.ecc.aws.gotopple.com
spec:
  group: ecc.aws.gotopple.com
  names:
    kind: EIPAssociation
    plural: eipassociations
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            allocationName:
              type: string
            instanceName:
              type: string
          required:
          - allocationName
          - instanceName
          type: object
        status:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
