apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: ec2instances.ecc.aws.gotopple.com
spec:
  group: ecc.aws.gotopple.com
  names:
    kind: EC2Instance
    plural: ec2instances
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            imageId:
              type: string
            instanceType:
              type: string
            maxCount:
              format: int64
              type: integer
            minCount:
              format: int64
              type: integer
            subnetId:
              type: string
            tagSpecification:
              items:
                properties:
                  key:
                    type: string
                  value:
                    type: string
                required:
                - key
                - value
                type: object
              type: array
          required:
          - imageId
          - instanceType
          - maxCount
          - minCount
          - subnetId
          - tagSpecification
          type: object
        status:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
