apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: vpcs.ecc.aws.gotopple.com
spec:
  group: ecc.aws.gotopple.com
  names:
    kind: VPC
    plural: vpcs
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            cidrBlock:
              type: string
            enableDnsHostnames:
              type: boolean
            enableDnsSupport:
              type: boolean
            instanceTenancy:
              type: string
            tags:
              items:
                properties:
                  key:
                    type: string
                  value:
                    type: string
                required:
                - key
                - value
                type: object
              type: array
          required:
          - cidrBlock
          - enableDnsSupport
          - enableDnsHostnames
          - instanceTenancy
          - tags
          type: object
        status:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
