apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: volumes.ecc.aws.gotopple.com
spec:
  group: ecc.aws.gotopple.com
  names:
    kind: Volume
    plural: volumes
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            availabilityZone:
              type: string
            size:
              format: int64
              type: integer
            tags:
              items:
                properties:
                  key:
                    type: string
                  value:
                    type: string
                required:
                - key
                - value
                type: object
              type: array
            volumeType:
              type: string
          required:
          - availabilityZone
          - size
          - volumeType
          - tags
          type: object
        status:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
