apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: iamattachrolepolicies.iam.aws.gotopple.com
spec:
  group: iam.aws.gotopple.com
  names:
    kind: IAMAttachRolePolicy
    plural: iamattachrolepolicies
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            iamPolicyName:
              type: string
            iamRoleName:
              type: string
          required:
          - iamRoleName
          - iamPolicyName
          type: object
        status:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
