apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: iampolicies.iam.aws.gotopple.com
spec:
  group: iam.aws.gotopple.com
  names:
    kind: IAMPolicy
    plural: iampolicies
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            description:
              type: string
            path:
              type: string
            policyDocument:
              type: string
            policyName:
              type: string
          required:
          - description
          - path
          - policyDocument
          - policyName
          type: object
        status:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
