apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: swarmdefaults.swarm.aws.gotopple.com
spec:
  group: swarm.aws.gotopple.com
  names:
    kind: swarmDefaults
    plural: swarmdefaults
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        Subnet:
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              properties:
                availabilityZone:
                  type: string
                cidrBlock:
                  type: string
                mapPublicIpOnLaunch:
                  type: boolean
                tags:
                  items:
                    properties:
                      key:
                        type: string
                      value:
                        type: string
                    required:
                    - key
                    - value
                    type: object
                  type: array
                vpcName:
                  type: string
              required:
              - availabilityZone
              - cidrBlock
              - vpcName
              - tags
              type: object
            status:
              type: object
          type: object
        VPC:
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              properties:
                cidrBlock:
                  type: string
                enableDnsHostnames:
                  type: boolean
                enableDnsSupport:
                  type: boolean
                instanceTenancy:
                  type: string
                tags:
                  items:
                    properties:
                      key:
                        type: string
                      value:
                        type: string
                    required:
                    - key
                    - value
                    type: object
                  type: array
              required:
              - cidrBlock
              - enableDnsSupport
              - enableDnsHostnames
              - instanceTenancy
              - tags
              type: object
            status:
              type: object
          type: object
        apiVersion:
          type: string
        internetGateway:
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              properties:
                tags:
                  items:
                    properties:
                      key:
                        type: string
                      value:
                        type: string
                    required:
                    - key
                    - value
                    type: object
                  type: array
                vpcName:
                  type: string
              required:
              - tags
              - vpcName
              type: object
            status:
              type: object
          type: object
        internetGatewayAttachment:
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              properties:
                internetGatewayName:
                  type: string
                vpcName:
                  type: string
              required:
              - internetGatewayName
              - vpcName
              type: object
            status:
              type: object
          type: object
        kind:
          type: string
        metadata:
          type: object
        natGateway:
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              properties:
                eipAllocationName:
                  type: string
                subnetName:
                  type: string
                tags:
                  items:
                    properties:
                      key:
                        type: string
                      value:
                        type: string
                    required:
                    - key
                    - value
                    type: object
                  type: array
              required:
              - subnetName
              - eipAllocationName
              - tags
              type: object
            status:
              type: object
          type: object
        route:
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              properties:
                destinationCidrBlock:
                  type: string
                gatewayName:
                  type: string
                routeTableName:
                  type: string
              required:
              - destinationCidrBlock
              - gatewayName
              - routeTableName
              type: object
            status:
              type: object
          type: object
        routeTable:
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              properties:
                tags:
                  items:
                    properties:
                      key:
                        type: string
                      value:
                        type: string
                    required:
                    - key
                    - value
                    type: object
                  type: array
                vpcName:
                  type: string
              required:
              - vpcName
              - tags
              type: object
            status:
              type: object
          type: object
        routeTableAssociation:
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              properties:
                routeTableName:
                  type: string
                subnetName:
                  type: string
              required:
              - routeTableName
              - subnetName
              type: object
            status:
              type: object
          type: object
      required:
      - VPC
      - Subnet
      - internetGateway
      - internetGatewayAttachment
      - natGateway
      - routeTable
      - routeTableAssociation
      - route
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
