apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: dockerswarms.swarm.aws.gotopple.com
spec:
  group: swarm.aws.gotopple.com
  names:
    kind: DockerSwarm
    plural: dockerswarms
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            managerSize:
              type: string
            numManagers:
              format: int64
              type: integer
            numWorkers:
              format: int64
              type: integer
            swarmName:
              type: string
            workerSize:
              type: string
          required:
          - swarmName
          - numManagers
          - numWorkers
          - managerSize
          - workerSize
          type: object
        status:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
