apiVersion: ecc.aws.gotopple.com/v1alpha1
kind: EC2Instance
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: ec2instance-walkthrough
  namespace: kloudformation
spec:
  imageId: ami-6cd6f714 #Amazon Linux
  instanceType: t2.micro
  subnetName: subnet-walkthrough
  userData: 'sudo yum update -y &&
            sudo yum install docker -y &&
            sudo service docker start &&
            sudo usermod -a -G docker ec2-user &&
            sudo touch ~/test.txt'
  ec2KeyPair: keypair-walkthrough
  ec2SecurityGroupName: ec2securitygroup-walkthrough
  tags:
    - key: Name
      value: Kloudformation-Walkthough
