apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ecc.aws.gotopple.com
  resources:
  - eips
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ecc.aws.gotopple.com
  resources:
  - eipassociations
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ecc.aws.gotopple.com
  resources:
  - internetgateways
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ecc.aws.gotopple.com
  resources:
  - routes
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ecc.aws.gotopple.com
  resources:
  - routetables
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ecc.aws.gotopple.com
  resources:
  - subnets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ecc.aws.gotopple.com
  resources:
  - vpcs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
