apiVersion: ecc.aws.gotopple.com/v1alpha1
kind: InternetGateway
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: internetgateway-sample
spec:
  tags:
    - key: Name
      value: FACK
  vpcName: example-network
