apiVersion: ecc.aws.gotopple.com/v1alpha1
kind: EIPAssociation
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: eipassociation-sample
spec:
  allocationName: eip-sample
  ec2InstanceName: sample-ec2-instance
