apiVersion: ecc.aws.gotopple.com/v1alpha1
kind: NATGateway
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: natgateway-sample
spec:
  subnetName: example-network-public-a
  eipAllocationName: eip-sample
  tags:
    - key: Name
      value: Amazing-NAT-Gateway
