apiVersion: ecc.aws.gotopple.com/v1alpha1
kind: NATGateway
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: natgateway-sample
spec:
  SubnetName: example-network-public-a
  AllocationName: eip-sample2
