apiVersion: ecc.aws.gotopple.com/v1alpha1
kind: EC2Instance
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: ec2instance-sample
spec:
  imageId: ami-6cd6f714 #Amazon Linux
  instanceType: t2.micro
  maxCount: 1
  minCount: 1
  subnetName: example-network-public-a
  tags:
    - key: Name
      value: "Test Instance"
