apiVersion: ecc.aws.gotopple.com/v1alpha1
kind: InternetGatewayAttachment
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: internetgatewayattachment-sample
spec:
  # Add fields here
  foo: bar
