apiVersion: iam.aws.gotopple.com/v1alpha1
kind: AddRoleToInstanceProfile
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: addroletoinstanceprofile-sample
spec:
  iamInstanceProfileName: iaminstanceprofile-sample
  iamRoleName: role-sample
