apiVersion: iam.aws.gotopple.com/v1alpha1
kind: IAMInstanceProfile
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: iaminstanceprofile-sample
spec:
  instanceProfileName: "sample-instanceprofile"
  path: "/"
